### ISSUE TITLE
FORT using server mode cannot be interrupted on OpenBSD with SIGINT signal (Control+C)

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/FORT-validator#14]
When FORT is running in server mode on OpenBSD, if the user tries to interrupt the process sending a SIGINT signal (Control+C) the process keeps running as it is shown on the images below:

**FORT, server mode, rsync strategy off, local repository**

![interruptLog](https://user-images.githubusercontent.com/22969079/62966171-1718f380-bdcc-11e9-8ea6-a74a889e1fec.png)

**FORT, server mode, validating RIPE TAL**

![interruptLog2](https://user-images.githubusercontent.com/22969079/62966179-1a13e400-bdcc-11e9-90ad-6aae6a5c60a8.png)

**Comment by pcarana** [comment]
An extra signal handler was causing part of the issue, so it was removed in order to handle SIGINT as a SIGTERM (which seems to be the default behavior).

**Comment by TheRedTrainer** [comment]
Verified. When the user sends a SIGINT signal, the FORT process is interrupted as expected.
