### ISSUE TITLE
Log displays "Valid ROAs" label for valid prefixes info

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/FORT-validator#18]
When FORT is running in server mode and log level info, the following information about validation is logged: 

> INF: Validation finished:
> INF: - Valid ROAs: 3
> INF: - Valid Router Keys: 0
> INF: - Current serial number is 1.
> INF: - Real execution time: 0 secs.

The label "Valid ROAS" should be "Valid prefixes" because it is related to the number of prefixes validated in the last execution.

**Comment by pcarana** [comment]
This applies to branch v1.2.0 (currently under development)

**Comment by TheRedTrainer** [comment]
I'm sorry, My bad.

**Comment by ydahhrk** [comment]
Might want to make a [label](https://github.com/NICMx/Jool/issues?q=is%3Aissue+label%3A%22Applies+to+unreleased+code%22+is%3Aclosed) for this, so you don't need to keep these bugs "hidden."
