### ISSUE TITLE
Support https URIs in TALs

### ISSUE THREAD

**Issue by timbru** [NICMx/FORT-validator#19]
Hi,

Could you please support HTTPS in TALs as per:
https://tools.ietf.org/html/rfc8630

This would help us in automating end-to-end interop testing of our RPKI CA software (krill). Of course, we only have a test TA (and can work around the issue with effort). However, supporting this will also allow RIRs to publish their TA certs using HTTPS - which would allow for more robustness (e.g. CDNs).

Thanks
Tim

**Comment by pcarana** [comment]
Hi Tim,

No problem, we'll be working to support RFC 8630. Hopefully, and due to our current workload, this should be released by January or February.

We will keep the issue open until RFC 8630 is fully supported.

**Comment by geeohgeegeeoh** [comment]
thanks, this will be extremely useful for progressing deprecate-RSYNC.

**Comment by pcarana** [comment]
Released with [v1.2.0](https://github.com/NICMx/FORT-validator/releases/tag/v1.2.0) :+1:

**Comment by timbru** [comment]
Great, thanks!
