### ISSUE TITLE
Include ebuild for Gentoo

### ISSUE THREAD

**Issue by pcarana** [NICMx/FORT-validator#23]
Check the proposal made by @alarig (thanks for this!), and include it in the installation guide.

> Here is the ebuild, in case you have comments: https://git.grifon.fr/alarig/SwordArMor-gentoo-overlay/src/branch/master/net-misc/FORT-validator/FORT-validator-1.1.3.ebuild
> I didn’t added the other sandbox options, as I don’t see how to do this simply.
> 
> I will drop the filecaps workaround when the “user-fork” will be released.
> 
> _Originally posted by @alarig in https://github.com/NICMx/FORT-validator/issues/22#issuecomment-586758613_

**Comment by alarig** [comment]
I’ve created a PR on the gentoo repo to include my ebuild in the mail. But as it’s the first time I’m doing this, I don’t know how long it will take before merge, nor if it will be accepted at all.

**Comment by pcarana** [comment]
Well, thanks for being so proactive! Let's hope there isn't any problems adding your ebuild, please let us know the progress of your proposal.

**Comment by alarig** [comment]
Hi,

My ebuild has been accepted on the GURU repo (which is maintained by users, see https://wiki.gentoo.org/wiki/Project:GURU): https://gitweb.gentoo.org/repo/proj/guru.git/tree/net-misc/FORT-validator/FORT-validator-1.2.0.ebuild

The MR is still open on the official repo.

**Comment by pcarana** [comment]
Wow, those are great news! :smiley: Congrats for your ebuild, we will add the reference soon.

I will let you know here when this is done.
