### ISSUE TITLE
Fails to build with gcc 10

### ISSUE THREAD

**Issue by rfc1036** [NICMx/FORT-validator#32]
The package fails to build in a test rebuild on at least amd64 with gcc-10/g++-10, but succeeds to build with gcc-9/g++-9.

The full build log can be found at: http://people.debian.org/~doko/logs/gcc10-20200225/fort-validator_1.2.0-1_unstable_gcc10.log

To build with GCC 10, either set CC=gcc-10 CXX=g++-10 explicitly,
or install the gcc, g++, gfortran, ... packages from experimental.

  apt-get -t=experimental install g++

Common build failures are new warnings resulting in build failures with
-Werror turned on, or new/dropped symbols in Debian symbols files.
For other C/C++ related build failures see the porting guide at
http://gcc.gnu.org/gcc-10/porting_to.html

<pre>
/usr/bin/ld: slurm/fort-db_slurm.o:./src/slurm/db_slurm.c:36: multiple definition of `addr_buf'; fort-output_printer.o:./src/output_printer.c:11: first defined here
</pre>

**Comment by rfc1036** [comment]
This is [Debian bug #957221](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957221).

**Comment by pcarana** [comment]
Thanks for the report, we'll be reviewing the errors and the warnings as well.

**Comment by dhfelix** [comment]
We have solved the warnings and have been able to compile with GCC 10 without displaying any new warnings or errors.

The fix will be uploaded with FORT version 1.2.1, soon to be released.
