### ISSUE TITLE
Probemas con TALs de RIPE y APNIC

### ISSUE THREAD

**Issue by moviedo-sc** [NICMx/FORT-validator#45]
Hola, estoy recibiendo los siguientes errores con los TALs de APNIC y RIPE, que terminar haciendo que FORT se detenga:

Dec 10 12:49:37 RPKI-Fort fort[12327]: Dec 10 12:49:37 ERR: /etc/fort/tal/apnic.tal: None of the URIs of the TAL '/etc/fort/tal/apnic.tal' yielded a successful traversal.
Dec 10 12:49:37 RPKI-Fort fort[12327]: Dec 10 12:49:37 ERR: /etc/fort/tal/ripe.tal: None of the URIs of the TAL '/etc/fort/tal/ripe.tal' yielded a successful traversal.

Volví a descargar los archivos TAL pero continúa el error. 

Versión: 1.4.2-1
SO: Ubuntu 20.04
 
Les agradezco la ayuda.

**Comment by pcarana** [comment]
Hola @moviedo-sc ,

Para tener un poco más de información al respecto, podrías agregar por favor los siguientes argumentos al ejecutar FORT:
- Si estás ejecutando el binario directamente: `--log.level=info --validation-log.enabled --validation-log.level=info`.
- Si instalaste FORT como un servicio, agregar en `/etc/fort/config.json`:
```
"log": {
  "level": "info"
},
"validation-log": {
  "enabled": true,
  "level": "info"
}
```

**Comment by moviedo-sc** [comment]
Gracias por la rápida respuesta. Aquí el output:

ec 10 13:00:53 RPKI-Fort systemd[1]: Starting FORT RPKI validator...
Dec 10 13:00:53 RPKI-Fort systemd[1]: Started FORT RPKI validator.
Dec 10 13:11:38 RPKI-Fort ntpd[210]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted
Dec 10 13:17:37 RPKI-Fort fort[12573]: Dec 10 13:17:37 ERR: Error sending Cache Response PDU to client.
Dec 10 13:17:37 RPKI-Fort fort[12573]: Dec 10 13:17:37 ERR:   - Connection reset by peer
Dec 10 13:22:12 RPKI-Fort ntpd[210]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted
Dec 10 13:26:12 RPKI-Fort systemd[1]: Stopping FORT RPKI validator...
Dec 10 13:26:12 RPKI-Fort systemd[1]: fort.service: Succeeded.
Dec 10 13:26:12 RPKI-Fort systemd[1]: Stopped FORT RPKI validator.
Dec 10 13:26:12 RPKI-Fort systemd[1]: Starting FORT RPKI validator...
Dec 10 13:26:13 RPKI-Fort systemd[1]: Started FORT RPKI validator.
Dec 10 13:26:13 RPKI-Fort fort[13119]: ERR: JSON error on line 14, column 6: '}' expected near '"log"'
Dec 10 13:26:13 RPKI-Fort fort[13119]: Dec 10 13:26:13 ERR: JSON error on line 14, column 6: '}' expected near '"log"'
Dec 10 13:26:13 RPKI-Fort fort[13119]: Dec 10 13:26:13 ERR: Try '/usr/bin/fort --usage' or '/usr/bin/fort --help' for more information.
Dec 10 13:26:13 RPKI-Fort fort[13119]: ERR: Try '/usr/bin/fort --usage' or '/usr/bin/fort --help' for more information.
Dec 10 13:26:13 RPKI-Fort systemd[1]: fort.service: Main process exited, code=exited, status=254/n/a
Dec 10 13:26:13 RPKI-Fort systemd[1]: fort.service: Failed with result 'exit-code'.
Dec 10 13:27:44 RPKI-Fort systemd[1]: Starting FORT RPKI validator...
Dec 10 13:27:44 RPKI-Fort systemd[1]: Started FORT RPKI validator.
Dec 10 13:27:44 RPKI-Fort fort[13155]: ERR: JSON error on line 12, column 5: string or '}' expected near '}'
Dec 10 13:27:44 RPKI-Fort fort[13155]: Dec 10 13:27:44 ERR: JSON error on line 12, column 5: string or '}' expected near '}'
Dec 10 13:27:44 RPKI-Fort fort[13155]: Dec 10 13:27:44 ERR: Try '/usr/bin/fort --usage' or '/usr/bin/fort --help' for more information.
Dec 10 13:27:44 RPKI-Fort fort[13155]: ERR: Try '/usr/bin/fort --usage' or '/usr/bin/fort --help' for more information.
Dec 10 13:27:44 RPKI-Fort systemd[1]: fort.service: Main process exited, code=exited, status=254/n/a
Dec 10 13:27:44 RPKI-Fort systemd[1]: fort.service: Failed with result 'exit-code'.
Dec 10 13:29:11 RPKI-Fort systemd[1]: Starting FORT RPKI validator...
Dec 10 13:29:11 RPKI-Fort systemd[1]: Started FORT RPKI validator.
Dec 10 13:29:12 RPKI-Fort fort[13169]: INF: Console log output configured; disabling validation logging on syslog.
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: Console log output configured; disabling validation logging on syslog.
Dec 10 13:29:12 RPKI-Fort fort[13169]: INF: (Validation Logs will be sent to the standard streams only.)
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: (Validation Logs will be sent to the standard streams only.)
Dec 10 13:29:12 RPKI-Fort fort[13169]: INF: Console log output configured; disabling operation logging on syslog.
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: Console log output configured; disabling operation logging on syslog.
Dec 10 13:29:12 RPKI-Fort fort[13169]: INF: (Operation Logs will be sent to the standard streams only.)
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: (Operation Logs will be sent to the standard streams only.)
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: Configuration {
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: tal: /etc/fort/tal
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: local-repository: /var/lib/fort
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: sync-strategy: root-except-ta
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: shuffle-uris: false
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: maximum-certificate-depth: 32
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: slurm: (null)
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: mode: server
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: work-offline: false
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: server.address:
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   10.148.148.102
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: server.port: 8323
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: server.backlog: 64
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: server.interval.validation: 900
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: server.interval.refresh: 900
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: server.interval.retry: 600
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: server.interval.expire: 7200
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: rsync.enabled: true
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: rsync.priority: 50
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: rsync.strategy: root-except-ta
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: rsync.retry.count: 2
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: rsync.retry.interval: 5
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: rsync.program: rsync
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: rsync.arguments-recursive:
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   --recursive
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   --delete
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   --times
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   --contimeout=20
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   --timeout=15
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   $REMOTE
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   $LOCAL
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: rsync.arguments-flat:
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   --times
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   --contimeout=20
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   --timeout=15
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   --dirs
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   $REMOTE
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   $LOCAL
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: rrdp.enabled: true
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: rrdp.priority: 60
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: rrdp.retry.count: 2
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: rrdp.retry.interval: 5
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: http.enabled: true
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: http.priority: 60
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: http.retry.count: 2
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: http.retry.interval: 5
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: http.user-agent: fort/1.4.2
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: http.connect-timeout: 30
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: http.transfer-timeout: 0
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: http.idle-timeout: 15
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: http.ca-path: (null)
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: log.enabled: true
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: log.output: console
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: log.level: info
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: log.tag: (null)
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: log.facility: daemon
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: log.file-name-format: global-url
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: log.color-output: false
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: validation-log.enabled: true
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: validation-log.output: console
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: validation-log.level: info
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: validation-log.tag: Validation
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: validation-log.facility: daemon
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: validation-log.file-name-format: global-url
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: validation-log.color-output: false
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: Custom incidences:
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   incid-hashalg-has-params (Signed Object's hash algorithm has NULL object as parameters): ignore
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   incid-obj-not-der-encoded (Object isn't DER encoded): ignore
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   incid-file-at-mft-not-found (File listed at manifest doesn't exist): error
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   incid-file-at-mft-hash-not-match (File hash listed at manifest doesn't match the actual file hash): error
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   incid-mft-stale (The current time is after the nextUpdate field at the manifest): error
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF:   incid-crl-stale (The current time is after the nextUpdate field at the CRL): error
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: output.roa: (null)
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: output.bgpsec: (null)
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: asn1-decode-max-stack: 4096
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: stale-repository-period: 43200
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: }
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: Attempting to bind socket to address '10.148.148.102', port '8323'.
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: Success; bound to address '10.148.148.102', port '8323'.
Dec 10 13:29:12 RPKI-Fort fort[13169]: Dec 10 13:29:12 INF: Starting validation.
Dec 10 13:29:17 RPKI-Fort ntpd[210]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted
Dec 10 13:29:32 RPKI-Fort fort[13169]: Dec 10 13:29:32 ERR [Validation]: /etc/fort/tal/ripe.tal: [RSYNC exec]: rsync error: timeout waiting for daemon connection (code 35) at socket.c(281) [Receiver=3.1.3]
Dec 10 13:29:32 RPKI-Fort fort[13169]: Dec 10 13:29:32 WRN [Validation]: /etc/fort/tal/ripe.tal: Retrying RSYNC 'rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer' in 5 seconds, 2 attempts remaining.
Dec 10 13:29:32 RPKI-Fort fort[13169]: Dec 10 13:29:32 ERR [Validation]: /etc/fort/tal/apnic.tal: [RSYNC exec]: rsync error: timeout waiting for daemon connection (code 35) at socket.c(281) [Receiver=3.1.3]
Dec 10 13:29:32 RPKI-Fort fort[13169]: Dec 10 13:29:32 WRN [Validation]: /etc/fort/tal/apnic.tal: Retrying RSYNC 'rsync://rpki.apnic.net/repository/apnic-rpki-root-iana-origin.cer' in 5 seconds, 2 attempts remaining.
Dec 10 13:29:32 RPKI-Fort fort[13169]: Dec 10 13:29:32 ERR [Validation]: /etc/fort/tal/arin.tal: [RSYNC exec]: rsync error: timeout waiting for daemon connection (code 35) at socket.c(281) [Receiver=3.1.3]
Dec 10 13:29:32 RPKI-Fort fort[13169]: Dec 10 13:29:32 WRN [Validation]: /etc/fort/tal/arin.tal: Retrying RSYNC 'rsync://rpki.arin.net/repository/arin-rpki-ta.cer' in 5 seconds, 2 attempts remaining.
Dec 10 13:29:39 RPKI-Fort fort[13169]: Dec 10 13:29:39 ERR [Validation]: rsync://rpki-repo.registro.br/repo/DhUX35ZMUCbRhYuECLQuQiyiqCX4z9LvRirJw3bBUwyX/0/6DAA6C0C733120C8AD8C5E70A08E3FB2F403E62D.mft: CRL is stale/expired
Dec 10 13:29:39 RPKI-Fort fort[13169]: Dec 10 13:29:39 ERR [Validation]: rsync://rpki-repo.registro.br/repo/9oV3uvReVxtqSEKudAwKVMKYABjc3Ckq68cx1SU1ZPz2/0/5DC8CFAD03643912C8549AE531ED176EFEF7AC5E.mft: CRL is stale/expired
Dec 10 13:29:40 RPKI-Fort fort[13169]: Dec 10 13:29:40 ERR [Validation]: rsync://rpki-repo.registro.br/repo/E2BKb6etUQTwHEXJBP82DKSb8MSzPJP4JSwwZsnK65rm/0/524736929299BF82CC58720416F5FEC4C0FDEC6B.mft: CRL is stale/expired
Dec 10 13:29:41 RPKI-Fort fort[13169]: Dec 10 13:29:41 ERR [Validation]: rsync://rpki-repo.registro.br/repo/5K2diqeiYDg7D2PBfWfwTa4Lr6MQEWcridkNhGxF8tg2/0/FCBFA22B1391531C891453DE95DA8CACDE58D28C.mft: CRL is stale/expired
Dec 10 13:29:42 RPKI-Fort fort[13169]: Dec 10 13:29:42 ERR [Validation]: /etc/fort/tal/afrinic.tal: Error requesting URL https://rpki.afrinic.net/repository/AfriNIC.cer: Connection timed out after 30000 milliseconds
Dec 10 13:29:42 RPKI-Fort fort[13169]: Dec 10 13:29:42 WRN [Validation]: /etc/fort/tal/afrinic.tal: Retrying HTTP request 'https://rpki.afrinic.net/repository/AfriNIC.cer' in 5 seconds, 2 attempts remaining.
Dec 10 13:29:46 RPKI-Fort fort[13169]: Dec 10 13:29:46 ERR [Validation]: rsync://rpki-repo.registro.br/repo/Ej1Zzxt4qWJD2J4HaQegVmhtrkQfjPkXRnEXW1xGSC1h/0/6EBE21EC5A5E2B1F815B3F8F3D961486CEBA02A1.mft: CRL is stale/expired
Dec 10 13:29:47 RPKI-Fort fort[13169]: Dec 10 13:29:47 ERR [Validation]: rsync://rpki-repo.registro.br/repo/GxS1HkbMUJ74HqafsjbKn3WrRLrnUmMb2aPfDQ1Gx6PY/0/A220A91CDBE4A681034F2485AB70CACD72E17E09.mft: CRL is stale/expired
Dec 10 13:29:57 RPKI-Fort fort[13169]: Dec 10 13:29:57 ERR [Validation]: /etc/fort/tal/ripe.tal: [RSYNC exec]: rsync error: timeout waiting for daemon connection (code 35) at socket.c(281) [Receiver=3.1.3]
Dec 10 13:29:57 RPKI-Fort fort[13169]: Dec 10 13:29:57 WRN [Validation]: /etc/fort/tal/ripe.tal: Retrying RSYNC 'rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer' in 5 seconds, 1 attempts remaining.
Dec 10 13:29:57 RPKI-Fort fort[13169]: Dec 10 13:29:57 ERR [Validation]: /etc/fort/tal/apnic.tal: [RSYNC exec]: rsync error: timeout waiting for daemon connection (code 35) at socket.c(281) [Receiver=3.1.3]
Dec 10 13:29:57 RPKI-Fort fort[13169]: Dec 10 13:29:57 WRN [Validation]: /etc/fort/tal/apnic.tal: Retrying RSYNC 'rsync://rpki.apnic.net/repository/apnic-rpki-root-iana-origin.cer' in 5 seconds, 1 attempts remaining.
Dec 10 13:30:09 RPKI-Fort fort[13169]: Dec 10 13:30:09 ERR [Validation]: rsync://rpki.arin.net/repository/arin-rpki-ta.cer: Error requesting URL https://rrdp.arin.net/notification.xml: Connection timed out after 30001 milliseconds
Dec 10 13:30:09 RPKI-Fort fort[13169]: Dec 10 13:30:09 WRN [Validation]: rsync://rpki.arin.net/repository/arin-rpki-ta.cer: Retrying HTTP request 'https://rrdp.arin.net/notification.xml' in 5 seconds, 2 attempts remaining.
Dec 10 13:30:17 RPKI-Fort fort[13169]: Dec 10 13:30:17 ERR [Validation]: /etc/fort/tal/afrinic.tal: Error requesting URL https://rpki.afrinic.net/repository/AfriNIC.cer: Connection timed out after 30000 milliseconds
Dec 10 13:30:17 RPKI-Fort fort[13169]: Dec 10 13:30:17 WRN [Validation]: /etc/fort/tal/afrinic.tal: Retrying HTTP request 'https://rpki.afrinic.net/repository/AfriNIC.cer' in 5 seconds, 1 attempts remaining.
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 ERR [Validation]: /etc/fort/tal/apnic.tal: [RSYNC exec]: rsync error: timeout waiting for daemon connection (code 35) at socket.c(281) [Receiver=3.1.3]
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 WRN [Validation]: /etc/fort/tal/apnic.tal: Max RSYNC retries (2) reached on 'rsync://rpki.apnic.net/repository/apnic-rpki-root-iana-origin.cer', won't retry again.
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 WRN [Validation]: /etc/fort/tal/apnic.tal: TAL URI 'rsync://rpki.apnic.net/repository/apnic-rpki-root-iana-origin.cer' could not be downloaded.
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 WRN [Validation]: /etc/fort/tal/apnic.tal: Looking for the TA certificate at the local files.
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 ERR [Validation]: /etc/fort/tal/apnic.tal: Could not open location '/var/lib/fort/rpki.apnic.net/repository/apnic-rpki-root-iana-origin.cer'
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 ERR [Validation]:   - No such file or directory
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 ERR: /etc/fort/tal/apnic.tal: None of the URIs of the TAL '/etc/fort/tal/apnic.tal' yielded a successful traversal.
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 ERR [Validation]: /etc/fort/tal/ripe.tal: [RSYNC exec]: rsync error: timeout waiting for daemon connection (code 35) at socket.c(281) [Receiver=3.1.3]
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 WRN [Validation]: /etc/fort/tal/ripe.tal: Max RSYNC retries (2) reached on 'rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer', won't retry again.
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 WRN [Validation]: /etc/fort/tal/ripe.tal: TAL URI 'rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer' could not be downloaded.
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 WRN [Validation]: /etc/fort/tal/ripe.tal: Looking for the TA certificate at the local files.
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 ERR [Validation]: /etc/fort/tal/ripe.tal: Could not open location '/var/lib/fort/rpki.ripe.net/ta/ripe-ncc-ta.cer'
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 ERR [Validation]:   - No such file or directory
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 ERR: /etc/fort/tal/ripe.tal: None of the URIs of the TAL '/etc/fort/tal/ripe.tal' yielded a successful traversal.
Dec 10 13:30:22 RPKI-Fort fort[13169]: Dec 10 13:30:22 WRN: Validation from TAL '/etc/fort/tal/ripe.tal' yielded error, discarding any other validation results.
Dec 10 13:30:44 RPKI-Fort fort[13169]: Dec 10 13:30:44 ERR [Validation]: rsync://rpki.arin.net/repository/arin-rpki-ta.cer: Error requesting URL https://rrdp.arin.net/notification.xml: Connection timed out after 30001 milliseconds
Dec 10 13:30:44 RPKI-Fort fort[13169]: Dec 10 13:30:44 WRN [Validation]: rsync://rpki.arin.net/repository/arin-rpki-ta.cer: Retrying HTTP request 'https://rrdp.arin.net/notification.xml' in 5 seconds, 1 attempts remaining.
Dec 10 13:31:27 RPKI-Fort fort[13169]: Dec 10 13:31:27 WRN: Validation from TAL '/etc/fort/tal/apnic.tal' yielded error, discarding any other validation results.
Dec 10 13:31:27 RPKI-Fort fort[13169]: Dec 10 13:31:27 INF: Validation finished:
Dec 10 13:31:27 RPKI-Fort fort[13169]: Dec 10 13:31:27 INF: - Valid Prefixes: 0
Dec 10 13:31:27 RPKI-Fort fort[13169]: Dec 10 13:31:27 INF: - Valid Router Keys: 0
Dec 10 13:31:27 RPKI-Fort fort[13169]: Dec 10 13:31:27 INF: - No serial number.
Dec 10 13:31:27 RPKI-Fort fort[13169]: Dec 10 13:31:27 INF: - Real execution time: 135 secs.
Dec 10 13:31:27 RPKI-Fort fort[13169]: Dec 10 13:31:27 ERR: First validation wasn't successful.
Dec 10 13:31:27 RPKI-Fort systemd[1]: fort.service: Main process exited, code=exited, status=234/n/a
Dec 10 13:31:27 RPKI-Fort systemd[1]: fort.service: Failed with result 'exit-code'.

**Comment by pcarana** [comment]
Gracias por compartir el output. Creo que hay dos cosas que revisar en la máquina host y la red:
- Mensaje `Dec 10 13:29:17 RPKI-Fort ntpd[210]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted`. Tal vez esto represente un problema al intentar descargar los archivos de los servidores indicados en los TALs.
- Por lo que veo no hubo problemas sincronizando con los servidores de LACNIC, pero sí con el resto de los TALs. ¿Hay algún firewall estricto para peticiones de salida en la red? Tal vez eso esté bloqueando las peticiones de salida por HTTPS y RSYNC al resto de los servidores.

**Comment by pcarana** [comment]
Hola @moviedo-sc , ¿has podido encontrar el problema?

**Comment by pcarana** [comment]
Cerrando el reporte debido a que no hay actualizaciones.

_Closing this issue due to the lack of related updates_.
