### ISSUE TITLE
rpki-validator has memory leaks when validating repository

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/FORT-validator#5]
Some memory leaks were discovered using Valgrind tool while rpki-validator is validating a repository. The output for valgrind report is included as attachments for this issue
[afrinic-valgrind-output.txt](https://github.com/ydahhrk/rpki-validator/files/2993768/afrinic-valgrind-output.txt)
[arin-valgrind-output.txt](https://github.com/ydahhrk/rpki-validator/files/2993772/arin-valgrind-output.txt)
[lacnic-valgrind-output.txt](https://github.com/ydahhrk/rpki-validator/files/2993773/lacnic-valgrind-output.txt)
[ripe-valgrind-output.txt](https://github.com/ydahhrk/rpki-validator/files/2993774/ripe-valgrind-output.txt)

**Comment by ydahhrk** [comment]
Test, please

**Comment by TheRedTrainer** [comment]
Verified. All the memory leaks were fixed. Valgrind didn't found memory leaks anymore.
