### ISSUE TITLE
Docker hub still in 1.5.0

### ISSUE THREAD

**Issue by wibisono** [NICMx/FORT-validator#66]
Just FYI this is still at 1.5.0, from 9 months ago: https://hub.docker.com/r/nicmx/fort-validator

Maybe it's time to push the latest.

**Comment by ydahhrk** [comment]
Rats.

Looks like I wasn't handed down the username and password of the account.

Think I might have to create a new one.

**Comment by ydahhrk** [comment]
Ok, I should be granted access to the account around next Tuesday.

**Comment by ydahhrk** [comment]
Ok, got it early.

It's pushed. Can you please review it?

**Comment by wibisono** [comment]
Sorry was not keeping track of this :) 
LGTM, closing the issue.
