### ISSUE TITLE
Router can't connect to FORT validator

### ISSUE THREAD

**Issue by michelpy** [NICMx/FORT-validator#93]
Hi,

I downloaded and installed 1.5.4 (fort_1.5.4-1_amd64.deb). Ubuntu server 20.04.
Downloaded the tals.

Starting it:
root@looking-glass:/home/xxxx# fort --mode=server --server.address=192.168.228.15 --server.port=8323 --tal=/etc/fort/tal    
Apr  5 13:13:10 INF: Disabling validation logging on syslog.
Apr  5 13:13:10 INF: Disabling validation logging on standard streams.
Apr  5 13:13:10 INF: Console log output configured; disabling operation logging on syslog.
Apr  5 13:13:10 INF: (Operation Logs will be sent to the standard streams only.)
Apr  5 13:13:10 WRN: First validation cycle has begun, wait until the next notification to connect your router(s)
Apr  5 13:20:53 WRN: First validation cycle successfully ended, now you can connect your router(s)

Configured router : Cisco 4321 / Cisco IOS XE Software, Version 17.06.03a
router bgp 65532
 bgp rpki server tcp 192.168.228.15 port 8323 refresh 600

c4321-michel#sh ip bgp rpki servers
BGP SOVC neighbor is 192.168.228.15/8323 connected to port 8323
Flags 0, Refresh time is 600, Serial number is 0, Session ID is 0
InQ has 0 messages, OutQ has 0 messages, formatted msg 0
Session IO flags 0, Session flags 4000
 Neighbor Statistics:
  Prefixes 0
  Connection attempts: 10
  Connection failures: 10
  Errors sent: 0
  Errors received: 0
  No active TCP connection

It does not connect. I tried plenty of things, could use some help troubleshooting.

Thanks !

**Comment by ydahhrk** [comment]
Can you sniff the traffic between them?

**Comment by michelpy** [comment]
Hi Alberto,

It definitely is a router issue. Sniffing required some setup, FORT validator in VMWare workstation guest. But the router does not even try to connect to the FORT VM. When I have a solution I will post here.

**Comment by michelpy** [comment]
I was a VM/firewall issue :-(
The other issue I had was that I had to read about installing openssl1.1 on Ubuntu 22.04, but no big deal.
I am going to close this, but I still have an issue running FORT as a service.
Thanks!
