### ISSUE TITLE
traps / segfault under up-to-date debian 11

### ISSUE THREAD

**Issue by Rico29** [NICMx/FORT-validator#99]
Hello
fort validator often crashes with an error in kernel.log :

[208832.537689] traps: fort[663] trap stack segment ip:5592b3bf81d0 sp:7f8dcfc08640 error:0 in fort[5592b3bd6000+44000]

using fort 1.5.3 from debian 11 repositories

any idea how to debug that ?
Regards

**Comment by rfc1036** [comment]
For a start, please upgrade to 1.5.4 which you can find in the Debian 11 backports archive (https://backports.debian.org/) or in Debian 12.

**Comment by ydahhrk** [comment]
Did Fort print something in `/var/log/syslog`?

**Comment by ydahhrk** [comment]
As stated in the [1.6.0 release notes](https://github.com/NICMx/FORT-validator/releases/tag/1.6.0), I have found and patched several instances of undefined behavior during the reviews. There is no way to prove that these caused this particular crash (particularly considering that I never managed to reproduce it, and the OP already probably left), but the code has changed so much, at this point I expect the bug to manifest in a completely different way, if at all.

Please upgrade to the latest version. If it crashes again, please open a new bug.
